-- ============================================================================
-- LOGISTICA PERONA -- import de transportes de referencia por provincia
-- (planilla "Provincia, Ciudad, Lugar de Origen, Lugar de Destino, Rutas de
-- Destino, Empresa/Operador, Contacto, Vehiculo, Tipo de Carga, Tiempo de
-- Entrega, Costo Aproximado"), una fila = un transporte, cubriendo las 24
-- provincias + CABA.
--
-- Requiere haber corrido antes migration_transportes_referencia.sql (agrega
-- origin_coverage/route_numbers/delivery_time/cost_reference a `transports`).
--
-- Mapeo de columnas de la planilla a la base:
--   Provincia/Ciudad      -> transports.province / transports.city
--   Lugar de Origen       -> transports.origin_coverage (cobertura de retiro)
--   Lugar de Destino      -> transports.zone (cobertura de destino, mismo
--                             campo que ya se usa para "Bahia Blanca a
--                             Ushuaia", "NOA + sucursales...", etc.)
--   Rutas de Destino      -> transports.route_numbers (numeros de ruta/autovia)
--   Empresa / Operador    -> transports.name (se deja el nombre tal cual,
--                             incluyendo combinaciones "Andreani / Correo
--                             Argentino" -- no se separan sin tener certeza
--                             de que son la misma cobertura)
--   Contacto               -> transports.contact
--   Vehiculo               -> transports.vehicle_types (mapeado a las claves
--                             existentes camion/auto/moto + las nuevas
--                             furgon/utilitario/combi/camioneta)
--   Tipo de Carga          -> transports.type (mismo campo que ya se usa para
--                             "Camion completo, paqueteria, etc.")
--   Tiempo de Entrega      -> transports.delivery_time
--   Costo Aproximado       -> transports.cost_reference (texto de referencia,
--                             NO la tarifa estructurada de transport_rates)
--
-- Rutas en el mapa: el "Lugar de Destino" de la planilla es siempre una
-- region amplia o varios lugares a la vez (ej. "Todo el pais", "CABA /
-- Cordoba / NOA") y nunca un punto unico -- inventar una coordenada de
-- destino seria data ficticia. Se usa el mismo mecanismo que ya tiene la
-- app para este caso (ver src/app.js -> routeOriginMarkers): se crea una
-- `route` con origen geolocalizado (coordenadas conocidas de la ciudad) y
-- destino NULL, con el texto de cobertura en `label`. En el mapa de cada
-- transporte esto se ve como un marcador de origen con el detalle de la
-- cobertura en el popup, en vez de una linea inventada.
--
-- Seguro de re-ejecutar: usa ON CONFLICT (code) DO NOTHING en ambas tablas,
-- no duplica filas ni pisa datos existentes. No modifica ningun transporte
-- ya cargado (T001-T026) -- estos son transportes nuevos (T027 en adelante).
-- Pegar y ejecutar completo en: Supabase -> SQL Editor -> New query -> Run
-- ============================================================================

-- 1) Transportes (30 filas, una por combinacion provincia/ciudad de la planilla)
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('5f9264b2-413e-5dbe-87b0-7f7c4229bccd', 'T027', 'Andreani / Correo Argentino', 'Paqueteria / Bultos / Pallets', '0810-122-2637', 'CABA', 'CABA', 'Todo el pais', 'CABA / GBA', 'Ruta 9 / Ruta 7 / Ruta 3 / Ruta 14', '24 a 96 hs', '$6.500 - $45.000 (segun peso y distancia)', '{auto,moto,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('72d34ee5-a7ce-5c5e-af97-2421bc34fe2a', 'T028', 'Expreso Morabito / Rutacargo', 'Paqueteria / Bultos / Pallets', '011-4942-2627', 'Buenos Aires', 'La Plata', 'Todo el pais', 'Prov. de Buenos Aires', 'Ruta 2 / Ruta 3 / Ruta 226', '24 a 72 hs', '$7.000 - $50.000', '{auto,moto,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('e0a48997-0e54-5667-9a80-8c69d82e1f29', 'T029', 'Urbano / Andreani', 'Paqueteria / Bultos', '0810-222-8722', 'Catamarca', 'San Fernando del Valle', 'CABA / Cordoba / NOA', 'Catamarca', 'Ruta 38 / Ruta 60', '48 a 96 hs', '$8.000 - $35.000', '{moto,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('e8b159ce-2588-5e7f-aec1-e91371d6ec3f', 'T030', 'Expreso Singer / Urbano', 'Paqueteria / Bultos / Pallets', '0810-222-8722', 'Chaco', 'Resistencia', 'CABA / Rosario / NOA', 'Chaco', 'Ruta 11 / Ruta 16', '48 a 72 hs', '$8.500 - $40.000', '{camion,furgon}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('49429d37-86fa-532f-9618-22de2e8a9550', 'T031', 'Cruz del Sur / Via Cargo', 'Paqueteria / Bultos / Pallets', '0810-222-2789', 'Chubut', 'Comodoro Rivadavia', 'CABA / Buenos Aires', 'Chubut', 'Ruta 3', '72 a 120 hs', '$10.000 - $65.000', '{camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('233dc156-55ca-56f6-a8d9-6911d116c558', 'T032', 'Transporte Olivero / Sardi', 'Encomiendas / Paquetes', '03564-420653', 'Cordoba', 'San Francisco', 'Cordoba Cap. / Rosario / Sta. Fe', 'San Francisco', 'Ruta 19 / Ruta 158', '24 hs (Same Day / Next Day)', '$4.500 - $18.000', '{utilitario,combi}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('b18241f8-038c-5182-8be0-ff36b146d68f', 'T033', 'Car-Pack / Expreso Lancioni', 'Paqueteria / Sobres / Pallets', '0810-555-2277', 'Cordoba', 'Cordoba Cap.', 'Rosario / CABA / Interior Cba', 'Cordoba', 'Ruta 9 / Auto. Cordoba-Rosario', '24 a 48 hs', '$5.000 - $30.000', '{furgon,utilitario,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('b20929e0-e448-53f1-a504-5d68d33b0994', 'T034', 'Centro de Comisionistas VM', 'Puerta a puerta / Bultos', '0353-464-7960', 'Cordoba', 'Villa Maria', 'Cordoba Cap. / CABA / Rosario', 'Villa Maria', 'Ruta 9 / Ruta 158', '24 hs', '$4.000 - $16.000', '{auto,utilitario}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('fbb7f76d-6380-5999-ba3a-fd2580a6d14d', 'T035', 'OCA / Andreani', 'Paqueteria / Bultos / Pallets', '0810-999-7700', 'Corrientes', 'Corrientes Cap.', 'CABA / Brasil / Misiones', 'Corrientes', 'Ruta 12 / Ruta 14', '48 a 96 hs', '$8.000 - $45.000', '{auto,moto,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('80eeb5f2-6105-5001-b81c-7a8ce70572a4', 'T036', 'Expreso San Jose / Urbano', 'Paqueteria / Bultos / Pallets', '0810-222-8722', 'Entre Rios', 'Parana', 'CABA / Santa Fe / Corrientes', 'Entre Rios', 'Ruta 12 / Ruta 14 / Tunel Subfluvial', '24 a 48 hs', '$6.000 - $28.000', '{auto,moto,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('1530dcb4-0348-59b2-a7a6-565b638abc07', 'T037', 'Via Cargo / Correo Argentino', 'Paqueteria / Bultos', '0810-222-7722', 'Formosa', 'Formosa Cap.', 'CABA / Chaco / Santa Fe', 'Formosa', 'Ruta 11', '48 a 96 hs', '$8.500 - $38.000', '{moto,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('1b99f46b-bd15-56a9-9e2e-f253f44a562c', 'T038', 'Expreso Rivadavia', 'Bultos / Pallets', '0388-593-0742', 'Jujuy', 'San Salvador', 'NOA / CABA / Cordoba', 'Jujuy', 'Ruta 9 / Ruta 34', '48 a 96 hs', '$9.000 - $55.000', '{camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('0eec99b7-48bb-5cc5-bf5a-ed2efe1fd05c', 'T039', 'Transporte El Pampero', 'Paqueteria / Bultos / Pallets', '02954-551010', 'La Pampa', 'Santa Rosa', 'CABA / Cordoba / B. Blanca', 'La Pampa', 'Ruta 5 / Ruta 35', '24 a 72 hs', '$7.500 - $32.000', '{camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('37b15405-ec0a-58dc-9752-a9dc6e062990', 'T040', 'Andesmar Cargas', 'Paqueteria / Bultos / Pallets', '0810-122-4300', 'La Rioja', 'La Rioja Cap.', 'CABA / Cordoba / NOA', 'La Rioja', 'Ruta 38 / Ruta 74', '48 a 72 hs', '$8.000 - $35.000', '{moto,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('119f2314-4db6-55c4-b1b8-0c5007f3b547', 'T041', 'Andesmar Cargas / Bisacay', 'Paqueteria / Bultos / Pallets', '0810-122-4300', 'Mendoza', 'Mendoza Cap.', 'CABA / Cordoba / Chile', 'Mendoza', 'Ruta 7 / Ruta 40', '48 a 72 hs', '$8.500 - $42.000', '{auto,moto,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('bd93f23e-c6db-5e78-b0e1-f09e68d78289', 'T042', 'Expreso Singer / OCA', 'Paqueteria / Bultos / Pallets', '0810-999-7700', 'Misiones', 'Posadas', 'CABA / Rosario / Cordoba', 'Misiones', 'Ruta 12 / Ruta 14', '48 a 96 hs', '$9.000 - $48.000', '{auto,moto,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('130c8ea8-2b62-5418-bf8f-fe73868a0f5e', 'T043', 'Cruz del Sur / Via Cargo', 'Paqueteria / Bultos / Pallets', '0810-222-2789', 'Neuquen', 'Neuquen Cap.', 'CABA / B. Blanca / Cuyo', 'Neuquen', 'Ruta 22 / Ruta 151', '48 a 96 hs', '$9.500 - $50.000', '{auto,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('76dc2f79-6ce3-5cc8-8370-aa1dddb4e8e9', 'T044', 'Via Cargo / Cruz del Sur', 'Paqueteria / Bultos / Pallets', '0810-222-7722', 'Rio Negro', 'Cipolletti', 'CABA / Neuquen / Patagonia', 'Rio Negro', 'Ruta 22 / Ruta 3', '48 a 96 hs', '$9.000 - $48.000', '{camion,furgon}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('8d543a41-3fe8-52c9-8b4f-8485d39c2eca', 'T045', 'Expreso Rivadavia / La Sevilla', 'Bultos / Pallets', '0387-5840654', 'Salta', 'Salta Cap.', 'CABA / Cordoba / Tucuman', 'Salta', 'Ruta 9 / Ruta 34', '48 a 96 hs', '$9.000 - $55.000', '{camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('97727a42-99af-56e5-9cd1-c1086a1a5aee', 'T046', 'TAC / Andesmar Cargas', 'Paqueteria / Bultos / Pallets', '0810-122-4300', 'San Juan', 'San Juan Cap.', 'CABA / Mendoza / Cordoba', 'San Juan', 'Ruta 40 / Ruta 20', '48 a 72 hs', '$8.500 - $40.000', '{auto,moto,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('0c084d97-6baa-561f-a745-e9bfd8eece9c', 'T047', 'Urbano / Andreani', 'Paqueteria / Bultos / Pallets', '0810-222-8722', 'San Luis', 'San Luis Cap.', 'CABA / Mendoza / Cordoba', 'San Luis', 'Ruta 7 / Ruta 148', '24 a 72 hs', '$7.500 - $35.000', '{moto,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('c55cafd1-01e2-5827-943f-756ab8d3a8bb', 'T048', 'Cruz del Sur / Expreso Oro Negro', 'Paqueteria / Bultos / Pallets', '0810-222-2789', 'Santa Cruz', 'Rio Gallegos', 'CABA / Tierra del Fuego', 'Santa Cruz', 'Ruta 3', '96 a 144 hs', '$12.000 - $75.000', '{camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('da5d9ff2-7ce8-5da4-b195-38caa50a5664', 'T049', 'Comisionista Pirsa / Transporte Rioja', 'Paqueteria / Bultos / Pallets', '0341-15-337-7865', 'Santa Fe', 'Rosario', 'CABA / GBA / NOA', 'Rosario', 'Ruta 9 / Ruta 11 / Ruta 33', '24 a 48 hs', '$4.500 - $25.000', '{camioneta,furgon,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('c1aa247f-d87f-5fec-a049-d95f1d1e357f', 'T050', 'Senco S.A. Comisiones', 'Encomiendas / Puerta a puerta', '03464-42-8543', 'Santa Fe', 'Casilda', 'Rosario / Santa Fe Cap.', 'Casilda', 'Ruta 33 / Ruta 9', '24 hs', '$3.800 - $12.000', '{utilitario,auto}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('83e8dc39-e364-5cc0-86fc-476b8496e790', 'T051', 'Expreso Rivadavia', 'Bultos / Pallets', '0385-5063962', 'Santiago del Estero', 'Santiago Cap.', 'CABA / Tucuman / Cordoba', 'Santiago del Estero', 'Ruta 9 / Ruta 34', '48 a 72 hs', '$8.500 - $45.000', '{camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('7c5d7b24-a8a5-5b9c-b571-cd89cd09aa42', 'T052', 'Cruz del Sur / Lider Express', 'Paqueteria / Bultos / Pallets', '0810-222-2789', 'Tierra del Fuego', 'Ushuaia', 'CABA / Patagonia', 'Tierra del Fuego', 'Ruta 3', '120 a 168 hs', '$15.000 - $90.000', '{camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('3f322dba-69bd-5665-a4a3-044fecdd1edd', 'T053', 'Servi-Pack NOA / Expreso El Rayo', 'Paqueteria / Bultos / Pallets', '0381-430-1122', 'Tucuman', 'San Miguel de Tucuman', 'CABA / Cuyo / Salta / Jujuy', 'Tucuman', 'Ruta 9 / Ruta 38 / Ruta 34', '24 a 72 hs', '$5.500 - $38.000', '{auto,utilitario,camion}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('7e1b4cf9-7850-53c0-95f5-16a8c59841b8', 'T054', 'Punto a Punto Express', 'E-commerce / Paqueteria / Sobres', '011-4709-1100', 'CABA', 'CABA', 'GBA / Interior cercano', 'CABA', 'Ruta 8 / Ruta 9 / Acceso Oeste', '24 hs (Mismo dia)', '$3.500 - $14.000', '{moto,furgon}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('cec84033-dd4a-554d-9c42-25a613f7a4e5', 'T055', 'Comisionista El Rapido', 'Paquetes / Encomiendas / Valores', '0223-475-2000', 'Buenos Aires', 'Mar del Plata', 'CABA / La Plata / Tandil', 'Mar del Plata', 'Ruta 2 / Ruta 226', '24 hs', '$5.000 - $20.000', '{utilitario,combi}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into transports (id, code, name, type, contact, province, city, zone, origin_coverage, route_numbers, delivery_time, cost_reference, vehicle_types, source, verified_at) values ('8ad99b4e-cd75-572c-9646-7999ef24a3dc', 'T056', 'Expreso Lujan Express', 'Paqueteria liviana / Repuestos', '0261-431-5050', 'Mendoza', 'Mendoza Cap.', 'San Juan / San Luis', 'Mendoza', 'Ruta 40 / Ruta 7', '24 a 48 hs', '$5.500 - $22.000', '{camioneta,furgon}', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;

-- 2) Rutas (una por transporte, origen geolocalizado + cobertura de destino en label)
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('5f9264b2-413e-5dbe-87b0-7f7c4229bccd', 'R100', 'CABA', 'CABA', -34.6037, -58.3816, NULL, NULL, NULL, NULL, 'Todo el pais', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('72d34ee5-a7ce-5c5e-af97-2421bc34fe2a', 'R101', 'Buenos Aires', 'La Plata', -34.9215, -57.9545, NULL, NULL, NULL, NULL, 'Todo el pais', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('e0a48997-0e54-5667-9a80-8c69d82e1f29', 'R102', 'Catamarca', 'San Fernando del Valle', -28.4696, -65.7852, NULL, NULL, NULL, NULL, 'CABA / Cordoba / NOA', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('e8b159ce-2588-5e7f-aec1-e91371d6ec3f', 'R103', 'Chaco', 'Resistencia', -27.4514, -58.9867, NULL, NULL, NULL, NULL, 'CABA / Rosario / NOA', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('49429d37-86fa-532f-9618-22de2e8a9550', 'R104', 'Chubut', 'Comodoro Rivadavia', -45.8641, -67.4964, NULL, NULL, NULL, NULL, 'CABA / Buenos Aires', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('233dc156-55ca-56f6-a8d9-6911d116c558', 'R105', 'Cordoba', 'San Francisco', -31.4273, -62.0836, NULL, NULL, NULL, NULL, 'Cordoba Cap. / Rosario / Sta. Fe', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('b18241f8-038c-5182-8be0-ff36b146d68f', 'R106', 'Cordoba', 'Cordoba Cap.', -31.4201, -64.1888, NULL, NULL, NULL, NULL, 'Rosario / CABA / Interior Cba', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('b20929e0-e448-53f1-a504-5d68d33b0994', 'R107', 'Cordoba', 'Villa Maria', -32.4076, -63.2426, NULL, NULL, NULL, NULL, 'Cordoba Cap. / CABA / Rosario', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('fbb7f76d-6380-5999-ba3a-fd2580a6d14d', 'R108', 'Corrientes', 'Corrientes Cap.', -27.4806, -58.8341, NULL, NULL, NULL, NULL, 'CABA / Brasil / Misiones', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('80eeb5f2-6105-5001-b81c-7a8ce70572a4', 'R109', 'Entre Rios', 'Parana', -31.7333, -60.5238, NULL, NULL, NULL, NULL, 'CABA / Santa Fe / Corrientes', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('1530dcb4-0348-59b2-a7a6-565b638abc07', 'R110', 'Formosa', 'Formosa Cap.', -26.1775, -58.1781, NULL, NULL, NULL, NULL, 'CABA / Chaco / Santa Fe', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('1b99f46b-bd15-56a9-9e2e-f253f44a562c', 'R111', 'Jujuy', 'San Salvador', -24.1858, -65.2995, NULL, NULL, NULL, NULL, 'NOA / CABA / Cordoba', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('0eec99b7-48bb-5cc5-bf5a-ed2efe1fd05c', 'R112', 'La Pampa', 'Santa Rosa', -36.6167, -64.2833, NULL, NULL, NULL, NULL, 'CABA / Cordoba / B. Blanca', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('37b15405-ec0a-58dc-9752-a9dc6e062990', 'R113', 'La Rioja', 'La Rioja Cap.', -29.4131, -66.8558, NULL, NULL, NULL, NULL, 'CABA / Cordoba / NOA', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('119f2314-4db6-55c4-b1b8-0c5007f3b547', 'R114', 'Mendoza', 'Mendoza Cap.', -32.8908, -68.8272, NULL, NULL, NULL, NULL, 'CABA / Cordoba / Chile', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('bd93f23e-c6db-5e78-b0e1-f09e68d78289', 'R115', 'Misiones', 'Posadas', -27.3671, -55.8961, NULL, NULL, NULL, NULL, 'CABA / Rosario / Cordoba', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('130c8ea8-2b62-5418-bf8f-fe73868a0f5e', 'R116', 'Neuquen', 'Neuquen Cap.', -38.9516, -68.0591, NULL, NULL, NULL, NULL, 'CABA / B. Blanca / Cuyo', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('76dc2f79-6ce3-5cc8-8370-aa1dddb4e8e9', 'R117', 'Rio Negro', 'Cipolletti', -38.9377, -67.9903, NULL, NULL, NULL, NULL, 'CABA / Neuquen / Patagonia', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('8d543a41-3fe8-52c9-8b4f-8485d39c2eca', 'R118', 'Salta', 'Salta Cap.', -24.7859, -65.4117, NULL, NULL, NULL, NULL, 'CABA / Cordoba / Tucuman', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('97727a42-99af-56e5-9cd1-c1086a1a5aee', 'R119', 'San Juan', 'San Juan Cap.', -31.5375, -68.5364, NULL, NULL, NULL, NULL, 'CABA / Mendoza / Cordoba', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('0c084d97-6baa-561f-a745-e9bfd8eece9c', 'R120', 'San Luis', 'San Luis Cap.', -33.295, -66.3356, NULL, NULL, NULL, NULL, 'CABA / Mendoza / Cordoba', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('c55cafd1-01e2-5827-943f-756ab8d3a8bb', 'R121', 'Santa Cruz', 'Rio Gallegos', -51.623, -69.2168, NULL, NULL, NULL, NULL, 'CABA / Tierra del Fuego', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('da5d9ff2-7ce8-5da4-b195-38caa50a5664', 'R122', 'Santa Fe', 'Rosario', -32.9468, -60.6393, NULL, NULL, NULL, NULL, 'CABA / GBA / NOA', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('c1aa247f-d87f-5fec-a049-d95f1d1e357f', 'R123', 'Santa Fe', 'Casilda', -33.0333, -61.1667, NULL, NULL, NULL, NULL, 'Rosario / Santa Fe Cap.', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('83e8dc39-e364-5cc0-86fc-476b8496e790', 'R124', 'Santiago del Estero', 'Santiago Cap.', -27.7951, -64.2615, NULL, NULL, NULL, NULL, 'CABA / Tucuman / Cordoba', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('7c5d7b24-a8a5-5b9c-b571-cd89cd09aa42', 'R125', 'Tierra del Fuego', 'Ushuaia', -54.8019, -68.303, NULL, NULL, NULL, NULL, 'CABA / Patagonia', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('3f322dba-69bd-5665-a4a3-044fecdd1edd', 'R126', 'Tucuman', 'San Miguel de Tucuman', -26.8083, -65.2176, NULL, NULL, NULL, NULL, 'CABA / Cuyo / Salta / Jujuy', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('7e1b4cf9-7850-53c0-95f5-16a8c59841b8', 'R127', 'CABA', 'CABA', -34.6037, -58.3816, NULL, NULL, NULL, NULL, 'GBA / Interior cercano', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('cec84033-dd4a-554d-9c42-25a613f7a4e5', 'R128', 'Buenos Aires', 'Mar del Plata', -38.0055, -57.5426, NULL, NULL, NULL, NULL, 'CABA / La Plata / Tandil', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, source, verified_at) values ('8ad99b4e-cd75-572c-9646-7999ef24a3dc', 'R129', 'Mendoza', 'Mendoza Cap.', -32.8908, -68.8272, NULL, NULL, NULL, NULL, 'San Juan / San Luis', 'Planilla de referencia (transportes por provincia)', '2026-09-20') on conflict (code) do nothing;
-- 3) Verificacion rapida (opcional, solo lectura)
-- select code, name, province, city, zone, route_numbers, delivery_time, cost_reference from transports where code like 'T0%' and code >= 'T027' order by code;
