-- ============================================================================
-- LOGÍSTICA PERONA — import de transportistas y rutas (Transportistas Argentina)
-- Pegar y ejecutar completo en: Supabase → SQL Editor → New query → Run
-- Es seguro re-ejecutarlo: usa ON CONFLICT (code) DO NOTHING, no duplica filas.
-- ============================================================================

-- 1) Columnas nuevas en transports (no rompen los datos existentes)
alter table transports add column if not exists code text unique;
alter table transports add column if not exists business_name text;
alter table transports add column if not exists cuit text;
alter table transports add column if not exists mobile text;
alter table transports add column if not exists whatsapp text;
alter table transports add column if not exists website text;
alter table transports add column if not exists province text;
alter table transports add column if not exists city text;
alter table transports add column if not exists address text;
alter table transports add column if not exists postal_code text;
alter table transports add column if not exists zone text;
alter table transports add column if not exists source text;
alter table transports add column if not exists verified_at date;

-- 2) Tabla nueva: rutas que recorre cada transportista
create table if not exists routes (
  id uuid primary key default gen_random_uuid(),
  code text unique,
  transport_id uuid references transports(id) on delete cascade,
  origin_province text,
  origin_city text,
  origin_lat double precision,
  origin_lng double precision,
  destination_province text,
  destination_city text,
  destination_lat double precision,
  destination_lng double precision,
  label text,
  frequency text,
  notes text,
  source text,
  verified_at date,
  created_at timestamptz not null default now()
);

-- 3) Seguridad + tiempo real, igual que el resto de las tablas
do $$
begin
  execute 'alter table routes enable row level security;';
  execute 'drop policy if exists "authenticated_all" on routes;';
  execute 'create policy "authenticated_all" on routes for all to authenticated using (true) with check (true);';
end $$;
alter publication supabase_realtime add table routes;

-- 4) Transportistas (26)
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('e823545d-64d6-5664-9ef1-c46c5b16b379', 'T001', 'Transportes Martin', NULL, NULL, 'Transportista', NULL, NULL, '+54 9 2616620433', '+54 9 2616620433', 'comercial@transportemartin.com.ar', 'https://transportemartin.com.ar/', 'Mendoza', 'Costa de Araujo', 'Urquiza 160', NULL, 'Argentina, Chile, Paraguay, Perú, Brasil (MERCOSUR)', 'Sitio oficial (transportemartin.com.ar)', '2026-09-15', 'Carga sobredimensionada, refrigerada, seca y contenedores. Mas de 30 camiones propios.') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('dde81848-5a86-536d-b1c9-5022a9f9318c', 'T002', 'Transporte Vesprini', NULL, NULL, 'Empresa de transporte', NULL, '011 4484-3515', NULL, NULL, 'info@transportevesprini.com.ar', 'https://www.transportevesprini.com.ar/', 'Buenos Aires', 'San Justo', 'General Madariaga 3531', NULL, 'Bahía Blanca a Ushuaia, sucursales en toda la Patagonia', 'Sitio oficial (transportevesprini.com.ar)', '2026-09-15', 'También opera división Transcont (refrigerados). Mas de 250 tractores.') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('7a74444b-d0c8-5879-a888-8a14ebe8d5c3', 'T003', 'Transportes Unión', 'Transportes Unión S.A.', NULL, 'Empresa de transporte', NULL, NULL, NULL, NULL, NULL, 'https://www.transportesunion.com.ar/', 'Buenos Aires', 'CABA (Casa Central)', 'Lisandro de la Torre 3945', '1439', 'Patagonia: Comodoro Rivadavia, Trelew, Puerto Madryn, Caleta Olivia, Neuquén', 'Sitio oficial (transportesunion.com.ar)', '2026-09-15', 'Servicio diario expreso BA-Patagonia, 6 sucursales, 25 destinos, entrega en 36hs. No publican teléfono en el sitio.') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('2da5e97e-87e4-56be-a49d-6ffcb0d930fc', 'T004', 'Puma Cargo', NULL, NULL, 'Comisionista', NULL, '+54 11 5199-4070', NULL, NULL, 'contacto@pumacargo.com.ar', 'https://www.pumacargo.com.ar/', 'Buenos Aires', 'CABA (San Telmo)', 'Lima 1125 Piso 1 Of C', 'C1073AAW', 'Internacional (aéreo, marítimo, terrestre): Argentina, Brasil, Bolivia, Chile, Perú, Paraguay, Uruguay', 'Sitio oficial (pumacargo.com.ar)', '2026-09-15', 'Operador logístico internacional (forwarder), no transportista directo. Cargas peligrosas, perecederas, proyecto.') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('34d773a3-c1ee-5b6e-8b6d-4d45f33d4539', 'T005', 'Expreso Biletta', 'Expreso Biletta SRL', NULL, 'Transportista', NULL, '+54 3571 500913', NULL, '+54 9 3571 310082', NULL, 'https://expresobiletta.com.ar/', 'Córdoba', NULL, NULL, NULL, 'Córdoba - Buenos Aires - Rosario', 'Sitio oficial (expresobiletta.com.ar)', '2026-09-15', 'Entrega Córdoba-BA 48hs, Rosario 72hs, express 24hs a consultar. Clientes: Bridgestone, AGD, Weatherford.') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('5efc02d7-d94b-5cf4-a16c-fb586ac25066', 'T006', 'Cavallin Internacional', NULL, NULL, 'Comisionista', NULL, '(341) 2134-084', NULL, '(341) 2134-084', 'cavallininternacional.ventas@gmail.com', 'https://www.cavallin-internacional.com/', 'Santa Fe', 'Rosario', 'España 19 Piso 1 Of D', 'S2000', 'Argentina-Brasil-Chile-Paraguay (Mercosur)', 'Sitio oficial (cavallin-internacional.com)', '2026-09-15', 'Mas de 25 años de trayectoria. Oficinas en Rosario e Itaqui (Brasil). Carga IMO, sobredimensionada, contenedores.') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('e80ba376-c36c-577e-b778-cd4964788c07', 'T007', 'PP Transportes y Logística', NULL, NULL, 'Fletero', NULL, '+54 351 317-8363', NULL, NULL, NULL, NULL, 'Córdoba', 'Córdoba', NULL, 'X5000', 'Córdoba capital', 'Directorio logistica.dir.ar', '2026-09-15', 'Orientado a mudanzas/fletes locales en Córdoba.') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('c739b2f3-30a5-530e-9727-eafe9f406766', 'T008', 'TCN - Transporte Cargas del Norte', NULL, NULL, 'Empresa de transporte', NULL, '0381 5677739', NULL, '0381 4195919', 'consultas@transportecargasdelnorte.com', 'https://www.transportecargasdelnorte.com/', 'Tucumán', 'Tafí Viejo', 'Ruta Nacional 9 Km 1303', NULL, 'NOA + sucursales en Buenos Aires, Córdoba y Rosario', 'Sitio oficial (transportecargasdelnorte.com)', '2026-09-15', 'Sucursales: Parque Patricios (BA), Rincón 1459 (Córdoba), Virasoro 3340 (Rosario).') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('c9fbae5a-d330-55ee-ab42-41c14be1473d', 'T009', 'Transporte Acordis', 'Transporte Acordis S.A.', NULL, 'Transportista', NULL, '011-4301-4448', '11-4997-7774', NULL, 'contacto@transporteacordis.com', 'https://transporteacordis.com.ar/', 'Buenos Aires', 'CABA (Villa Soldati) / Maipú (Mendoza)', 'Julio Troxler 3220 (BA) / Rodriguez Peña 6210 (Mendoza)', NULL, 'Buenos Aires - Mendoza', 'Sitio oficial (transporteacordis.com.ar)', '2026-09-15', 'Salidas diarias BA-Mendoza. Deposito de 200m2. Tel Mendoza: 2614544222.') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('9e64e467-3321-5080-b294-78c706fb1f87', 'T010', 'Transporte Delfín', NULL, NULL, 'Empresa de transporte', NULL, NULL, '0299 15-6261830', NULL, 'contacto@transportedelfin.com', 'https://www.transportedelfin.com', 'Río Negro', 'General Fernández Oro', 'Ruta 22 Km 1208', '8325.0', 'Rosario (Santa Fe) - Neuquén - Alto Valle de Río Negro (Neuquén, Allen, Cipolletti, San Carlos de Bariloche, Junín de los Andes y otras localidades)', 'Guia Cores (guiacores.com.ar)', '2026-09-15', 'Carga seca, refrigerada, congelada y super-congelada puerta a puerta. Sucursal en Rosario: Oroño 4595, Santa Fe. Tel. secundario 0299 15-4530104.') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('6468156b-3792-5d1a-9f2e-06ade5b39eaa', 'T011', 'Transporte Orion', 'Orion de Transporte G y Z S.A.', NULL, 'Empresa de transporte', NULL, '011 4586-1700', NULL, NULL, 'bsas@transporteorion.com.ar', 'https://www.transporteorion.net/', 'Buenos Aires', 'CABA', 'Manuel R. Trelles 2669', NULL, 'Corredor Rosario - Cordoba - Buenos Aires', 'Sitio oficial (transporteorion.net)', '2026-09-15', 'Sucursales: Rosario (Colon 2631, tel 0341 481-9203, rosario@transporteorion.com.ar), Cordoba (Francisco de Arteaga 2860, tel 0351 588-2998, cordoba@transporteorion.com.ar).') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('7297acc2-885e-571b-b5e2-55f543a59ab8', 'T012', 'Transporte de Carga Don Seferino', 'Transporte de Carga Don Seferino S.R.L.', '30-71007268-6', 'Empresa de transporte', NULL, '0381 481-7151', NULL, NULL, 'donseferinosrl@yahoo.com.ar', 'https://www.transportedecargadonseferinosrl.com/', 'Tucumán', 'Lules', 'Ruta Prov. E-301 Km 23,5', NULL, 'Lules, Tucumán (sin otras rutas detalladas en sitio oficial)', 'Sitio oficial (transportedecargadonseferinosrl.com)', '2026-09-15', NULL) on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('88a1c8c7-2c92-543c-aa9f-81818eeae319', 'T013', 'Fletes y Servicios Pujato', 'Fletes y Servicios Pujato S.A.', '33-69566329-9', 'Fletero', NULL, '03464 49-4020', NULL, NULL, NULL, 'http://www.fletesyserviciospujato.com/', 'Santa Fe', 'Pujato', 'Saavedra 1221', NULL, 'A todos los puntos del pais (transporte nacional)', 'La Guia Online (laguiaonline.com.ar)', '2026-09-15', 'En el rubro desde 1997.') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('9e20c0f6-ece5-54d8-b64f-3092240afdf6', 'T014', 'Transportes Menconi', NULL, NULL, 'Empresa de transporte', NULL, '02226 42-2209', NULL, NULL, NULL, NULL, 'Buenos Aires', 'Cañuelas', 'San Martín 1333', NULL, 'Transporte de cargas liquidas a nivel nacional', 'La Guia Online (laguiaonline.com.ar)', '2026-09-15', 'Especializados en transporte de liquidos (mas de 80 años en el rubro, segun fuente).') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('b8ffcb78-deb2-53e3-9927-1d81dca94585', 'T015', 'Transportes Zamarian', 'Transportes Zamarian S.R.L.', '30-70799197-2', 'Empresa de transporte', NULL, '0261 497-8492', '+54 9 261 590-3859', NULL, 'administracion@transporteszamarian.com', 'https://www.transporteszamarian.com/', 'Mendoza', 'Luzuriaga (Maipú)', 'Mallea 553', NULL, 'Carga nacional e internacional via Uspallata - Paso Los Libertadores (Chile); refrigerada, seca y contenedores', 'Sitio oficial (transporteszamarian.com)', '2026-09-15', 'Segundo email: logistica@transporteszamarian.com. Tel. adicional +54 9 261 387-4755.') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('d4dcaed5-f71f-52c5-9c46-4d739e6dd764', 'T016', 'RAOSA', 'Transporte RAOSA SRL', NULL, 'Empresa de transporte', NULL, '03564 427524', '03564 15-572250', NULL, 'sanfco@raosa.com.ar', 'https://www.raosa.com.ar/', 'Córdoba', 'San Francisco', 'Salta 270', NULL, 'Red nacional con sucursales en Capital Federal, Rosario, Córdoba, San Francisco, Santa Fe y Formosa', 'Sitio oficial (raosa.com.ar)', '2026-09-15', 'Línea gratuita 0810-345-0012 (int. 4). Servicios: transporte de cargas, retiro de mercadería, contra-reembolso, depósito con control de stock.') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('6181e460-8e14-5d9c-b2d5-949cc7cae46a', 'T017', 'Transporte Morteros', NULL, NULL, 'Empresa de transporte', NULL, '03562 422470', NULL, NULL, NULL, 'https://transportemorteros.com.ar/', 'Córdoba', 'Morteros', 'Bv. Hipólito Yrigoyen 1331', '2421.0', 'Morteros-Córdoba, Morteros-San Francisco, Miramar-San Francisco, Ceres-Córdoba, Ceres-San Francisco; tambien turismo nacional e internacional', 'Sitio oficial (transportemorteros.com.ar)', '2026-09-15', 'Empresa fundada el 17/02/1948. Boleterias en Morteros (03562 422585), Cordoba (0351 4252166), Balnearia (03562 503960), Ceres (03491 420066) y San Francisco (03564 424090).') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('cd8c6b63-0da1-5edd-9f01-cf7dc2077f49', 'T018', 'BBB Express', NULL, NULL, 'Empresa de transporte', NULL, '3564 313209', NULL, NULL, 'comercial@bbbexpress.com.ar', 'https://www.bbbexpress.com.ar/', 'Córdoba', 'San Francisco', 'Santiago Pampiglione 4611, Parque Industrial', '2400.0', 'Córdoba, Buenos Aires, San Francisco, Rosario, Santa Fe; cobertura internacional Argentina-Uruguay', 'Sitio oficial (bbbexpress.com.ar)', '2026-09-15', 'Otros contactos: ventas@bbbexpress.com.ar, cordoba@bbbexpress.com.ar, buenosaires@bbbexpress.com.ar. Otros telefonos: 3564 647399, 3564 209852, 3564 522800.') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('945902c6-d4bd-5746-9188-f40bbffd758d', 'T019', 'Transporte Belgrano', 'Transportes Belgrano S.R.L.', '30-71555556-1', 'Empresa de transporte', NULL, NULL, '+54 9 3562 407127', '+54 9 3562 407127', NULL, NULL, 'Córdoba', 'Brinkmann', 'Dr Pitt Funes 985', NULL, 'Brinkmann - CABA - Córdoba - Morteros - Porteña - Rosario - Sunchales', 'Cargasnet.com.ar / Cuit Online', '2026-09-15', 'Deposito/sucursal en Cordoba Capital: Piero Astori 1300. Tambien depositos en Rosario y CABA.') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('92bee767-7f05-5059-a8e5-f6d7eba0938e', 'T020', 'Transporte Don Max', 'Transporte Don Max S.A.', '33-71090200-9', 'Empresa de transporte', NULL, '03564 43-0530', '011 2690-7766', NULL, NULL, 'https://www.transportedonmaxsa.com/', 'Córdoba', 'San Francisco', 'Gdor. San Martín 649', NULL, 'San Francisco, Córdoba (transporte de cargas); sin rutas detalladas en fuentes publicas', 'Guia Urbana (guiaurbana.com.ar) / Cuit Online', '2026-09-15', NULL) on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('6d4d299b-1af8-5fd5-9aa4-3704dac57749', 'T021', 'Transporte Santa Rita', NULL, NULL, 'Empresa de transporte', NULL, '(03564) 44-5876', NULL, NULL, NULL, 'https://www.santaritatransporte.com.ar/', 'Córdoba', 'San Francisco', 'Ing Huergo 1708', NULL, NULL, 'Guiaurbana.com.ar / sitio oficial (santaritatransporte.com.ar)', '2026-09-15', 'Transporte, distribución, depósito y logística') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('b78ea357-bfda-53f3-b502-77ad4a59ba74', 'T022', 'Expreso Brio', 'Expreso Brio SRL', NULL, 'Empresa de transporte', NULL, '0810-345-2746', NULL, NULL, NULL, 'http://expresobrio.com/', 'Córdoba', 'San Francisco', 'Pietro Finazzi 4683', NULL, 'Nacional (red de sucursales, incl. Córdoba Capital)', 'Sucursales24.com.ar / sitio oficial (expresobrio.com)', '2026-09-15', 'Empresa nacional de encomiendas y cargas; sucursal San Francisco Lun-Vie 08:00-17:00') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('6952e6ed-000f-533c-a6f3-7792aac964fc', 'T023', 'Expreso Micro Cargas', NULL, NULL, 'Empresa de transporte', NULL, '(03564) 47-9523', NULL, NULL, NULL, NULL, 'Córdoba', 'San Francisco', 'J Salk 870', NULL, NULL, 'Guiaurbana.com.ar', '2026-09-15', 'Sitio oficial (expresomicrocargas.com.ar) figura como "Próximamente", sin contenido') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('a0572a5a-7f0b-5b3a-90a6-9ff882f3dd8a', 'T024', 'Snaider Transportes', NULL, NULL, 'Empresa de transporte', NULL, '(03564) 43-566', NULL, NULL, NULL, NULL, 'Córdoba', 'San Francisco', 'Av J De Garay 2815', 'X2400DQM', NULL, 'Infoisinfo (san-francisco-cordoba.infoisinfo-ar.com)', '2026-09-15', 'Agencia de transporte') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('cd8a3288-543d-5ebe-8e1f-2ca1f25b6881', 'T025', 'Don Carmelo', 'Don Carmelo SRL', NULL, 'Empresa de transporte', NULL, '(03564) 43-483', NULL, NULL, NULL, NULL, 'Córdoba', 'San Francisco', 'Av 9 De Julio 1002', 'X2400AIX', NULL, 'Infoisinfo (san-francisco-cordoba.infoisinfo-ar.com)', '2026-09-15', 'Agencia de transporte') on conflict (code) do nothing;
insert into transports (id, code, name, business_name, cuit, type, contact, phone, mobile, whatsapp, email, website, province, city, address, postal_code, zone, source, verified_at, notes) values ('ca100896-f76e-51e0-80f4-1e8c7127fb8e', 'T026', 'Transporte Capello', NULL, NULL, 'Empresa de transporte', NULL, NULL, NULL, '+54 9 3564 473824', NULL, NULL, 'Córdoba', 'San Francisco', 'San Lorenzo 760', 'X2400', 'Córdoba y Santa Fe (distribución nacional agroindustria y comercio)', 'Cargasnet.com.ar', '2026-09-15', 'Cargas generales, distribución nacional para agroindustria y comercio') on conflict (code) do nothing;

-- 5) Rutas (46)
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('e823545d-64d6-5664-9ef1-c46c5b16b379', 'R001', 'Mendoza', 'Costa de Araujo', -32.9058, -68.423, NULL, NULL, NULL, NULL, 'Costa de Araujo (Mendoza) - Mercosur (Chile, Paraguay, Peru, Brasil)', NULL, NULL, 'Sitio oficial (transportemartin.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('dde81848-5a86-536d-b1c9-5022a9f9318c', 'R002', 'Buenos Aires', 'San Justo', -34.6802, -58.5599, NULL, NULL, NULL, NULL, 'San Justo (BA) - Corredor Bahia Blanca a Ushuaia (Patagonia)', NULL, NULL, 'Sitio oficial (transportevesprini.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('7a74444b-d0c8-5879-a888-8a14ebe8d5c3', 'R003', 'Buenos Aires', 'CABA', -34.6037, -58.3816, 'Chubut', 'Comodoro Rivadavia', -45.8641, -67.4964, 'CABA - Comodoro Rivadavia', NULL, NULL, 'Sitio oficial (transportesunion.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('7a74444b-d0c8-5879-a888-8a14ebe8d5c3', 'R004', 'Buenos Aires', 'CABA', -34.6037, -58.3816, 'Chubut', 'Trelew', -43.2489, -65.3051, 'CABA - Trelew', NULL, NULL, 'Sitio oficial (transportesunion.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('7a74444b-d0c8-5879-a888-8a14ebe8d5c3', 'R005', 'Buenos Aires', 'CABA', -34.6037, -58.3816, 'Chubut', 'Puerto Madryn', -42.7692, -65.0385, 'CABA - Puerto Madryn', NULL, NULL, 'Sitio oficial (transportesunion.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('7a74444b-d0c8-5879-a888-8a14ebe8d5c3', 'R006', 'Buenos Aires', 'CABA', -34.6037, -58.3816, 'Santa Cruz', 'Caleta Olivia', -46.4333, -67.5333, 'CABA - Caleta Olivia', NULL, NULL, 'Sitio oficial (transportesunion.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('7a74444b-d0c8-5879-a888-8a14ebe8d5c3', 'R007', 'Buenos Aires', 'CABA', -34.6037, -58.3816, 'Neuquen', 'Neuquen', -38.9516, -68.0591, 'CABA - Neuquen', NULL, NULL, 'Sitio oficial (transportesunion.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('2da5e97e-87e4-56be-a49d-6ffcb0d930fc', 'R008', 'Buenos Aires', 'CABA', -34.6037, -58.3816, NULL, NULL, NULL, NULL, 'CABA - Internacional (Brasil, Bolivia, Chile, Peru, Paraguay, Uruguay)', NULL, NULL, 'Sitio oficial (pumacargo.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('34d773a3-c1ee-5b6e-8b6d-4d45f33d4539', 'R009', 'Cordoba', 'Cordoba', -31.4201, -64.1888, 'Buenos Aires', NULL, NULL, NULL, 'Cordoba - Buenos Aires', NULL, 'Entrega 48hs', 'Sitio oficial (expresobiletta.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('34d773a3-c1ee-5b6e-8b6d-4d45f33d4539', 'R010', 'Cordoba', 'Cordoba', -31.4201, -64.1888, 'Santa Fe', 'Rosario', -32.9468, -60.6393, 'Cordoba - Rosario', NULL, 'Entrega 72hs, servicio express 24hs', 'Sitio oficial (expresobiletta.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('5efc02d7-d94b-5cf4-a16c-fb586ac25066', 'R011', 'Santa Fe', 'Rosario', -32.9468, -60.6393, NULL, NULL, NULL, NULL, 'Rosario - Internacional (Brasil, Chile, Paraguay - Mercosur)', NULL, NULL, 'Sitio oficial (cavallin-internacional.com)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('e80ba376-c36c-577e-b778-cd4964788c07', 'R012', 'Cordoba', 'Cordoba', -31.4201, -64.1888, 'Cordoba', 'Cordoba', -31.4201, -64.1888, 'Fletes locales - Cordoba Capital', NULL, NULL, 'Directorio logistica.dir.ar', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('c739b2f3-30a5-530e-9727-eafe9f406766', 'R013', 'Tucuman', 'Tafi Viejo', -26.7333, -65.2667, 'Buenos Aires', NULL, NULL, NULL, 'Tafi Viejo - Buenos Aires', NULL, NULL, 'Sitio oficial (transportecargasdelnorte.com)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('c739b2f3-30a5-530e-9727-eafe9f406766', 'R014', 'Tucuman', 'Tafi Viejo', -26.7333, -65.2667, 'Cordoba', NULL, NULL, NULL, 'Tafi Viejo - Cordoba', NULL, NULL, 'Sitio oficial (transportecargasdelnorte.com)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('c739b2f3-30a5-530e-9727-eafe9f406766', 'R015', 'Tucuman', 'Tafi Viejo', -26.7333, -65.2667, 'Santa Fe', 'Rosario', -32.9468, -60.6393, 'Tafi Viejo - Rosario', NULL, NULL, 'Sitio oficial (transportecargasdelnorte.com)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('c9fbae5a-d330-55ee-ab42-41c14be1473d', 'R016', 'Buenos Aires', 'CABA (Villa Soldati)', -34.665, -58.446, 'Mendoza', 'Maipu', -32.9833, -68.7833, 'CABA - Maipu (Mendoza)', NULL, NULL, 'Sitio oficial (transporteacordis.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('9e64e467-3321-5080-b294-78c706fb1f87', 'R017', 'Santa Fe', 'Rosario', -32.9468, -60.6393, 'Río Negro', 'General Fernández Oro', -38.9494, -67.9576, 'Rosario - Neuquen / Alto Valle de Rio Negro', NULL, 'Incluye mas de 30 localidades patagonicas (Neuquen, Allen, Cipolletti, Bariloche, Junin de los Andes, etc.)', 'Guia Cores (guiacores.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('6468156b-3792-5d1a-9f2e-06ade5b39eaa', 'R018', 'Buenos Aires', 'CABA', -34.6037, -58.3816, 'Santa Fe', 'Rosario', -32.9468, -60.6393, 'CABA - Rosario', NULL, NULL, 'Sitio oficial (transporteorion.net)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('6468156b-3792-5d1a-9f2e-06ade5b39eaa', 'R019', 'Buenos Aires', 'CABA', -34.6037, -58.3816, 'Córdoba', 'Córdoba', -31.4201, -64.1888, 'CABA - Cordoba', NULL, NULL, 'Sitio oficial (transporteorion.net)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('7297acc2-885e-571b-b5e2-55f543a59ab8', 'R020', 'Tucumán', 'Lules', -26.9167, -65.3333, 'Tucumán', 'Lules', -26.9167, -65.3333, 'Fletes locales - Lules, Tucuman', NULL, NULL, 'Sitio oficial (transportedecargadonseferinosrl.com)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('88a1c8c7-2c92-543c-aa9f-81818eeae319', 'R021', 'Santa Fe', 'Pujato', -32.95, -60.83, NULL, NULL, NULL, NULL, 'Pujato - Nacional (a todos los puntos del pais)', NULL, NULL, 'La Guia Online (laguiaonline.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('9e20c0f6-ece5-54d8-b64f-3092240afdf6', 'R022', 'Buenos Aires', 'Cañuelas', -35.0525, -58.7614, NULL, NULL, NULL, NULL, 'Cañuelas - Nacional (carga liquida)', NULL, NULL, 'La Guia Online (laguiaonline.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('b8ffcb78-deb2-53e3-9927-1d81dca94585', 'R023', 'Mendoza', 'Luzuriaga (Maipú)', -32.9958, -68.7852, NULL, NULL, NULL, NULL, 'Luzuriaga (Mendoza) - Internacional via Uspallata / Paso Los Libertadores (Chile)', NULL, NULL, 'Sitio oficial (transporteszamarian.com)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('d4dcaed5-f71f-52c5-9c46-4d739e6dd764', 'R024', 'Córdoba', 'San Francisco', -31.4266, -62.0836, 'CABA', 'Buenos Aires', -34.6037, -58.3816, 'San Francisco - Buenos Aires (CABA)', NULL, NULL, 'Sitio oficial (raosa.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('d4dcaed5-f71f-52c5-9c46-4d739e6dd764', 'R025', 'Córdoba', 'San Francisco', -31.4266, -62.0836, 'Santa Fe', 'Rosario', -32.9468, -60.6393, 'San Francisco - Rosario', NULL, NULL, 'Sitio oficial (raosa.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('d4dcaed5-f71f-52c5-9c46-4d739e6dd764', 'R026', 'Córdoba', 'San Francisco', -31.4266, -62.0836, 'Córdoba', 'Córdoba', -31.4201, -64.1888, 'San Francisco - Córdoba Capital', NULL, NULL, 'Sitio oficial (raosa.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('d4dcaed5-f71f-52c5-9c46-4d739e6dd764', 'R027', 'Córdoba', 'San Francisco', -31.4266, -62.0836, 'Santa Fe', 'Santa Fe', -31.6333, -60.7, 'San Francisco - Santa Fe', NULL, NULL, 'Sitio oficial (raosa.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('d4dcaed5-f71f-52c5-9c46-4d739e6dd764', 'R028', 'Córdoba', 'San Francisco', -31.4266, -62.0836, 'Formosa', 'Formosa', -26.1775, -58.1781, 'San Francisco - Formosa', NULL, NULL, 'Sitio oficial (raosa.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('6181e460-8e14-5d9c-b2d5-949cc7cae46a', 'R029', 'Córdoba', 'Morteros', -30.7167, -61.9833, 'Córdoba', 'Córdoba', -31.4201, -64.1888, 'Morteros - Córdoba Capital', NULL, NULL, 'Sitio oficial (transportemorteros.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('6181e460-8e14-5d9c-b2d5-949cc7cae46a', 'R030', 'Córdoba', 'Morteros', -30.7167, -61.9833, 'Córdoba', 'San Francisco', -31.4266, -62.0836, 'Morteros - San Francisco', NULL, NULL, 'Sitio oficial (transportemorteros.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('6181e460-8e14-5d9c-b2d5-949cc7cae46a', 'R031', 'Córdoba', 'Miramar', -30.8667, -62.6667, 'Córdoba', 'San Francisco', -31.4266, -62.0836, 'Miramar - San Francisco', NULL, NULL, 'Sitio oficial (transportemorteros.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('6181e460-8e14-5d9c-b2d5-949cc7cae46a', 'R032', 'Santa Fe', 'Ceres', -29.8833, -61.95, 'Córdoba', 'Córdoba', -31.4201, -64.1888, 'Ceres - Córdoba Capital', NULL, NULL, 'Sitio oficial (transportemorteros.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('6181e460-8e14-5d9c-b2d5-949cc7cae46a', 'R033', 'Santa Fe', 'Ceres', -29.8833, -61.95, 'Córdoba', 'San Francisco', -31.4266, -62.0836, 'Ceres - San Francisco', NULL, NULL, 'Sitio oficial (transportemorteros.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('cd8c6b63-0da1-5edd-9f01-cf7dc2077f49', 'R034', 'Córdoba', 'San Francisco', -31.4266, -62.0836, 'Córdoba', 'Córdoba', -31.4201, -64.1888, 'San Francisco - Córdoba Capital', NULL, NULL, 'Sitio oficial (bbbexpress.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('cd8c6b63-0da1-5edd-9f01-cf7dc2077f49', 'R035', 'Córdoba', 'San Francisco', -31.4266, -62.0836, 'CABA', 'Buenos Aires', -34.6037, -58.3816, 'San Francisco - Buenos Aires (CABA)', NULL, NULL, 'Sitio oficial (bbbexpress.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('cd8c6b63-0da1-5edd-9f01-cf7dc2077f49', 'R036', 'Córdoba', 'San Francisco', -31.4266, -62.0836, 'Santa Fe', 'Rosario', -32.9468, -60.6393, 'San Francisco - Rosario', NULL, NULL, 'Sitio oficial (bbbexpress.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('cd8c6b63-0da1-5edd-9f01-cf7dc2077f49', 'R037', 'Córdoba', 'San Francisco', -31.4266, -62.0836, 'Santa Fe', 'Santa Fe', -31.6333, -60.7, 'San Francisco - Santa Fe', NULL, NULL, 'Sitio oficial (bbbexpress.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('cd8c6b63-0da1-5edd-9f01-cf7dc2077f49', 'R038', 'Córdoba', 'San Francisco', -31.4266, -62.0836, NULL, NULL, NULL, NULL, 'San Francisco - Internacional (Uruguay)', NULL, NULL, 'Sitio oficial (bbbexpress.com.ar)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('945902c6-d4bd-5746-9188-f40bbffd758d', 'R039', 'Córdoba', 'Brinkmann', -31.7167, -62.0333, 'CABA', 'Buenos Aires', -34.6037, -58.3816, 'Brinkmann - Buenos Aires (CABA)', NULL, NULL, 'Cargasnet.com.ar', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('945902c6-d4bd-5746-9188-f40bbffd758d', 'R040', 'Córdoba', 'Brinkmann', -31.7167, -62.0333, 'Córdoba', 'Córdoba', -31.4201, -64.1888, 'Brinkmann - Córdoba Capital', NULL, NULL, 'Cargasnet.com.ar', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('945902c6-d4bd-5746-9188-f40bbffd758d', 'R041', 'Córdoba', 'Brinkmann', -31.7167, -62.0333, 'Córdoba', 'Morteros', -30.7167, -61.9833, 'Brinkmann - Morteros', NULL, NULL, 'Cargasnet.com.ar', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('945902c6-d4bd-5746-9188-f40bbffd758d', 'R042', 'Córdoba', 'Brinkmann', -31.7167, -62.0333, 'Córdoba', 'Porteña', -30.8667, -62.0333, 'Brinkmann - Porteña', NULL, NULL, 'Cargasnet.com.ar', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('945902c6-d4bd-5746-9188-f40bbffd758d', 'R043', 'Córdoba', 'Brinkmann', -31.7167, -62.0333, 'Santa Fe', 'Rosario', -32.9468, -60.6393, 'Brinkmann - Rosario', NULL, NULL, 'Cargasnet.com.ar', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('945902c6-d4bd-5746-9188-f40bbffd758d', 'R044', 'Córdoba', 'Brinkmann', -31.7167, -62.0333, 'Santa Fe', 'Sunchales', -30.9425, -61.5614, 'Brinkmann - Sunchales', NULL, NULL, 'Cargasnet.com.ar', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('b78ea357-bfda-53f3-b502-77ad4a59ba74', 'R045', 'Córdoba', 'San Francisco', -31.4266, -62.0836, NULL, NULL, NULL, NULL, 'San Francisco - Nacional (red de sucursales)', NULL, NULL, 'Sucursales24.com.ar / sitio oficial (expresobrio.com)', '2026-09-15') on conflict (code) do nothing;
insert into routes (transport_id, code, origin_province, origin_city, origin_lat, origin_lng, destination_province, destination_city, destination_lat, destination_lng, label, frequency, notes, source, verified_at) values ('ca100896-f76e-51e0-80f4-1e8c7127fb8e', 'R046', 'Córdoba', 'San Francisco', -31.4266, -62.0836, 'Santa Fe', NULL, NULL, NULL, 'San Francisco - Santa Fe (distribución regional agroindustria/comercio)', NULL, NULL, 'Cargasnet.com.ar', '2026-09-15') on conflict (code) do nothing;
