-- ============================================================================
-- LOGÍSTICA PERONA — completar datos faltantes de transportistas ya cargados
-- Migración ADITIVA: agrega columnas instagram/facebook (si no existen) y
-- completa SOLO los campos que estaban vacíos, con COALESCE (nunca pisa un
-- valor que ya tengas cargado). No borra ni reemplaza ningún transportista.
-- Pegar y ejecutar completo en: Supabase → SQL Editor → New query → Run
-- ============================================================================

alter table transports add column if not exists instagram text;
alter table transports add column if not exists facebook text;

update transports set postal_code = coalesce(postal_code, '5535'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T001';
update transports set cuit = coalesce(cuit, '30-69376173-1'), postal_code = coalesce(postal_code, 'B1754'), instagram = coalesce(instagram, 'https://www.instagram.com/transportevesprini/'), facebook = coalesce(facebook, 'https://www.facebook.com/TRANSPORTEVESPRINI/'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T002';
update transports set cuit = coalesce(cuit, '30-70892615-5'), phone = coalesce(phone, '(011) 2205-9250'), email = coalesce(email, 'ba@transportesunion.com.ar'), instagram = coalesce(instagram, 'https://www.instagram.com/transportes_union_sa/'), facebook = coalesce(facebook, 'https://www.facebook.com/TransportesUnionSA/'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T003';
update transports set cuit = coalesce(cuit, '30-71150289-7'), instagram = coalesce(instagram, 'https://www.instagram.com/pumacargo/'), facebook = coalesce(facebook, 'https://www.facebook.com/PumaCargo/'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T004';
update transports set cuit = coalesce(cuit, '30-66865399-1'), email = coalesce(email, 'info@expresobiletta.com.ar'), address = coalesce(address, 'Av. Pte. Arturo Illia 491'), city = coalesce(city, 'Río Tercero'), postal_code = coalesce(postal_code, 'X5850'), instagram = coalesce(instagram, 'https://www.instagram.com/expreso_biletta/'), facebook = coalesce(facebook, 'https://www.facebook.com/expresobiletta/'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T005';
update transports set instagram = coalesce(instagram, 'https://www.instagram.com/cavallin_internacional/'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T006';
update transports set facebook = coalesce(facebook, 'https://www.facebook.com/p/PP-Transportes-100057609212655/'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T007';
update transports set postal_code = coalesce(postal_code, '4103'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T008';
update transports set cuit = coalesce(cuit, '30-70986079-4'), instagram = coalesce(instagram, 'https://www.instagram.com/transporteacordis/'), facebook = coalesce(facebook, 'https://www.facebook.com/Transporte-Acordis-SA-107508935259898/'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T009';
update transports set phone = coalesce(phone, '+54 299 431-0038'), instagram = coalesce(instagram, 'https://www.instagram.com/transportedelfin/'), facebook = coalesce(facebook, 'https://www.facebook.com/TransporteDelfin/'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T010';
update transports set whatsapp = coalesce(whatsapp, '+54 11 3796-7499'), postal_code = coalesce(postal_code, 'C1416BSE'), instagram = coalesce(instagram, 'https://www.instagram.com/transporteorion.gyz/'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T011';
update transports set cuit = coalesce(cuit, '30-71007268-6'), postal_code = coalesce(postal_code, '4128'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T012';
update transports set cuit = coalesce(cuit, '33-69566329-9'), postal_code = coalesce(postal_code, '2123'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T013';
update transports set postal_code = coalesce(postal_code, '1814'), facebook = coalesce(facebook, 'https://www.facebook.com/p/Transportes-Menconi-100089764846655/'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T014';
update transports set cuit = coalesce(cuit, '30-70799197-2'), postal_code = coalesce(postal_code, '5513'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T015';
update transports set cuit = coalesce(cuit, '30-63341362-9'), postal_code = coalesce(postal_code, 'X2400'), instagram = coalesce(instagram, 'https://www.instagram.com/raosa_srl/'), facebook = coalesce(facebook, 'https://www.facebook.com/raosa.transporte/'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T016';
update transports set cuit = coalesce(cuit, '30-54644726-6'), mobile = coalesce(mobile, '11 5420-5519'), email = coalesce(email, 'consultas@transportemorteros.com.ar'), instagram = coalesce(instagram, 'https://www.instagram.com/transportemorteros/'), facebook = coalesce(facebook, 'https://www.facebook.com/EmpTransporteMorterosSrl/'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T017';
update transports set cuit = coalesce(cuit, '30-71585610-3'), mobile = coalesce(mobile, '+54 9 3518 506753'), instagram = coalesce(instagram, 'https://www.instagram.com/bbbexpress.ar/'), facebook = coalesce(facebook, 'https://www.facebook.com/TransporteBBBExpress/'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T018';
update transports set cuit = coalesce(cuit, '30-71555556-1'), phone = coalesce(phone, '(03562) 48-0100'), postal_code = coalesce(postal_code, '2419'), facebook = coalesce(facebook, 'https://www.facebook.com/profile.php?id=100038914940195'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T019';
update transports set cuit = coalesce(cuit, '33-71090200-9'), email = coalesce(email, 'info@transportedonmaxsa.com'), postal_code = coalesce(postal_code, '2400'), instagram = coalesce(instagram, 'https://www.instagram.com/transportedonmax/'), facebook = coalesce(facebook, 'https://www.facebook.com/transportedonmaxsa/'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T020';
update transports set postal_code = coalesce(postal_code, '2400'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T021';
update transports set postal_code = coalesce(postal_code, 'X2400'), notes = case when notes is null then 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' when notes like '%verificados el 2026-09-16%' then notes else notes || ' | ' || 'Datos adicionales (CUIT/contacto/redes) verificados el 2026-09-16 vía búsqueda web.' end where code = 'T022';
